################################################################################
# docker-compose up -d
################################################################################
version: '2'

networks:
  Kafka_Sasl_Network:
    driver: bridge

services:
  zookeeper_sasl:
    image: confluentinc/cp-zookeeper:6.1.0
    container_name: zookeeper_sasl
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SASL_ENABLED: "false"
      ZOOKEEPER_AUTH_PROVIDER_SASL: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_jaas.conf
    volumes:
      - ./Volumes/kafka_sasl/zookeeper_sasl/data:/data
      - ./Volumes/kafka_sasl/zookeeper_sasl/datalog:/datalog
      - ./config/zookeeper_jaas.conf:/etc/kafka/secrets/zookeeper_jaas.conf
    networks:
      - Kafka_Sasl_Network

  kafka_sasl:
    image: confluentinc/cp-kafka:6.1.0
    container_name: kafka_sasl
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: SASL_PLAINTEXT://:9092,PLAINTEXT://:29092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://localhost:9092,PLAINTEXT://kafka_sasl:29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_sasl:2181
      ZOOKEEPER_SASL_ENABLED: "false"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./config/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - ./Volumes/kafka_sasl/kafka_sasl/data:/var/lib/kafka/data
    depends_on:
      - zookeeper_sasl
    networks:
      - Kafka_Sasl_Network
