version: '3.8'

services:
  postgres:
    image: postgres:9.6.18-alpine
    container_name: postgres
    ports:
      - 5432:5432
    user: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 30s
      retries: 3
    command: [ "-c", "max_connections=300" ]
    volumes:
      - ./Volumes/postgres:/var/lib/postgresql/data 777
